<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CiaoService" targetNamespace="http://greeting.baile.usp/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:tns="http://greeting.baile.usp/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://greeting.baile.usp/" schemaLocation="ciao_xsd_1"/>
    </xsd:schema>
  </types>
  <message name="getGreetingResponse">
    <part name="parameters" element="tns:getGreetingResponse">
    </part>
  </message>
  <message name="getGreeting">
    <part name="parameters" element="tns:getGreeting">
    </part>
  </message>
  <portType name="Greeting">
    <operation name="getGreeting">
      <input message="tns:getGreeting" wsam:Action="http://greeting.baile.usp/Greeting/getGreetingRequest">
    </input>
      <output message="tns:getGreetingResponse" wsam:Action="http://greeting.baile.usp/Greeting/getGreetingResponse">
    </output>
    </operation>
  </portType>
  <binding name="CiaoPortBinding" type="tns:Greeting">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getGreeting">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CiaoService">
    <port name="CiaoPort" binding="tns:CiaoPortBinding">
      <soap:address location="http://localhost:1236/ciao"/>
    </port>
  </service>
</definitions>
